In [1]:
#Basic Operation on Images
import cv2
import numpy as np

img = cv2.imread('suji.jpg')

px = img[100,100]
print (px)

[ 69  87 128]


In [2]:
blue = img[100,100,0]
print (blue)

69


In [3]:
img[100,100] = [255,255,255]
print (img[100,100])

[255 255 255]


In [4]:
img[100,100]

array([255, 255, 255], dtype=uint8)

In [5]:
img.item(100,100,0)

255

In [6]:
img = cv2.imread('suji.jpg')

In [7]:
px = img[100,100]

In [8]:
img[100,100]

array([ 69,  87, 128], dtype=uint8)

In [9]:
img.item(100, 100, 0)

69

In [10]:
img.item(100, 100, 1)

87

In [11]:
img.item(100, 100, 2)

128

In [12]:
#img.itemset((:,:,2),0), Impossible 한번에 전부 바꿀 수 없음
#b,g,r = cv2.split(img)
#img = cv2.merge((b,g,r))
#b = img[:,:,0]
img[:,:,0] = 0

In [13]:
cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()